#!/bin/sh

# from quay.io/rshop/npm-alpine
#
# note: designed so that you can use the same image between npm and
# node

if [ "$1" = "pull" ]; then
  podman pull rshop/npm-alpine
fi

podman run --net host -v $HOME:$HOME -e HOME="$HOME" -w$(pwd) -it 147a node "$@"

